### ISSUE TITLE
Run Tests against Postgres database

### ISSUE THREAD

**Issue by pdrivom** [seapagan/fastapi-template#102] opened 2023-06-11 17:39 UTC
**Is your feature request related to a problem? Please describe.**
It would be better to use the same type of database to run tests. If any breaking changes on database connection layer (either code or package update) would not be hidden on tests.

**Describe the solution you'd like**
Switch from SQLite to Postgres.

**Extra info**
I can work on it.

**Comment by seapagan** [comment] 2023-06-11 20:22
This is planned.

I have this functionality already written (but commented out) in the `conftest.py`, and the `settings.py` is set up to read test database variables from the environment :

```python
# Setup the TEST Postgresql database.
test_db_user = "my_db_username"
test_db_password = "Sup3rS3cr3tP455w0rd"
test_db_address = "localhost"
test_db_port = "5432"
test_db_name = "api-template-test"
```

SQLite is a much easier system to set up as most users don't have a local Postgres database (yes, Docker makes that easier but again not everyone uses, can use, even or wants to use that).

I have been (and still am) concentrating on writing the tests. Once that is done, I will open the option to use Postgres for testing. myself :+1:

**Comment by seapagan** [comment] 2023-06-16 21:01
I was thinking about this just now as my brain was idling while boiling the kettle.

GitHub has the ability to run a Postgresql service during a GitHub action, so I can update the `Tests` Action to create and use this. A simple check in the `conftest.py` can detect if running under CI and switch to using that Postgres service.

I prefer to keep the local tests running SQLite by default - all access goes through the same ORM commands regardless of whether we are using Postgres or SQLite. The ORM maintainer updates the relevant driver as needed so there should not be breaking changes (and if so the online CI would catch it). The simple fact is not everyone can run a local Postgresql server or Docker.

However, I also will add an env variable like `FORCE_TEST_POSTGRESQL` or whatever that will switch to using Postgresql locally as well and can be picked up by the Docker container.

I also plan to remove all TEST_DB_xxx` variables except the TEST_DB_NAME, since they should be the same anyway.

Let me know if you see any issues with this, I'll prob get this into a feature branch and PR tomorrow

**Comment by seapagan** [comment] 2023-06-17 13:19
All the above was easily done, Postgres is working fine on GitHub actions and the tests will use it if in CI or the variable `TEST_WITH_POSTGRES` is True. 
The issue is that many tests fail (or async hang) under Postgres either locally or remotely. :sob: 

It is not an issue with the test cases or database incompatibility, but the way I am using async tests with the patched database. Hope to fix this today depending on time.
 
> GitHub has the ability to run a Postgresql service during a GitHub action, so I can update the `Tests` Action to create and use this. A simple check in the `conftest.py` can detect if running under CI and switch to using that Postgres service.
> 
> I prefer to keep the local tests running SQLite by default - all access goes through the same ORM commands regardless of whether we are using Postgres or SQLite. The ORM maintainer updates the relevant driver as needed so there should not be breaking changes (and if so the online CI would catch it). The simple fact is not everyone can run a local Postgresql server or Docker.
> 
> However, I also will add an env variable like `FORCE_TEST_POSTGRESQL` or whatever that will switch to using Postgresql locally as well and can be picked up by the Docker container.
> 
> I also plan to remove all `TEST_DB_xxx` variables except the `TEST_DB_NAME`, since they should be the same anyway.

**Comment by pdrivom** [comment] 2023-06-19 22:00
Hey @seapagan, yeah, I remember that, while playing around with tests.

Let me know if you need some help/ideas.

**Comment by seapagan** [comment] 2023-06-20 10:51
> Hey @seapagan, yeah, I remember that, while playing around with tests.
> 
> Let me know if you need some help/ideas.

I got sidetracked over the weekend on other projects and also completing #126 and implementing #127 (discussion at #128),

It's prob a simple fix to the `get_db` fixture and database provisioning, I hope to get back to this PR soonest.

**Comment by seapagan** [comment] 2023-07-11 09:13
Just an update on this ticket.

I'm working on PR #140, converting the database system to SQLAlchemy ORM (from encode/databases), which seems a better and more maintained way of getting Async database usage. I've also upgraded to SQLAlchemy 2.0, necessitating some fair code changes.

I'm currently working on getting the tests running. When that is merged, I'll back-port the Postgres testing from #125 as well which should finally close this ticket.

**Comment by seapagan** [comment] 2023-09-25 08:18
Another update :grin: 

GitHub actions are working fine on the 'develop' branch under Postgres. However, the Integration tests are turned off until I fix a few issues (Unit tests ok). I am overhauling the pytest setup/teardown config. I should get that sorted when I have time to work on it.

**Comment by seapagan** [comment] 2024-02-07 14:53
This has been completed with the `0.5.0` release. closing.

**Closed by seapagan** 2024-02-07 14:53 UTC
Labels: enhancement, github_actions
